version: "3.8"

services:
  account-service:
    build: ./account
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
    depends_on:
      - service-discovery

  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
    depends_on:
      - service-discovery
      - account-service

