version: "3.8"

services:
  account-service:
    build: ./account
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/demo/protocol/openid-connect/certs
    depends_on:
      - service-discovery

  service-discovery:
    build: ./service-discovery
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://service-discovery:8761/eureka
      - spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/demo/protocol/openid-connect/certs
      - spring.security.oauth2.client.provider.keycloak.issuer-uri=http://keycloak:8080/realms/demo
    depends_on:
      - service-discovery
      - account-service
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"

