server:
    port: 8080

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8082/realms/demo/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/demo
        registration:
          spring-with-test-scope:
            provider: keycloak
            client-id: spring-with-test-scope
            client-secret: IWLSnakHG8aNTWNaWuSj0a11UY4lzxd9
            authorization-grant-type: authorization_code
            scope: openid
  #          keycloak-without-test-scope:
  #            provider: keycloak
  #            client-id: spring-without-test-scope
  #            client-secret: f6fc369d-49ce-4132-8282-5b5d413eba23
  #            authorization-grant-type: authorization_code
  #            redirect-uri: "{baseUrl}/login/oauth2/code/spring-without-test-scope"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    root: DEBUG
